on: push
name: Build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - name: checkout
    - uses: actions/checkout@master
    - name: build
      uses: cedrickring/golang-action@1.6.0
