name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
        with:
          ref: develop
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x


      - run: go get -v -u ./...

      - run: go build -ldflags "-X main._buildDate=testDate -X main._buildVersion=testVersion" -o main *.go

